project:
  type: book  

lang: bg
book:
  title: "Въведение в математическата оптимизация"
  author: "Бойко Амаров"
  date: "4/02/2024"

  chapters:
    - index.qmd
    # - part: 01-Python/index.qmd
    - 02-Introduction/index.ipynb
    - 03-Graphical-Method/01-Blending.ipynb
    - 00-Assignments/assignments.ipynb
      # chapters:
      #   - 01-Python/01-01-Basics.ipynb
      #   - 01-Python/01-02-Basics-Ex.ipynb
      #   - 01-Python/01-03-Numpy.ipynb
      #   - 01-Python/01-04-Pandas.ipynb
      #   - 01-Python/01-05-Pandas-Ex.ipynb        
    # - 00-Homework-Instructions.qmd
    # - 02-Statistics-Review.qmd
    # - 01-Introduction-to-R.qmd
    # - 02a-Continuous-Distributions.qmd
    # - 03-Simple-Linear-Model.qmd
    # - 04-Simple-ANOVA.qmd
    # - 05-Hypothesis-Testing-and-CI.qmd
    - Literature.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    code-fold: true
    code-summary: "Покажи кода"

editor: visual
